version: 2.0.{build}

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  CODECOV_TOKEN:
    secure: n8BNBkzy0fQyKMckYgGMPbO9X1cToO9Sp7364AgfrCXZKlgkHeAX0APHuvYGr8jo

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  parallel: true
  verbosity: detailed

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\ReporterNext.Tests\bin\Debug\ReporterNext.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[ReporterNext.Tests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml"
